#!/bin/bash -e

if [ "${RELEASE}" == "" ] ; then
   export RELEASE="dev"
fi

REQUESTS=1000
# THREADS="8 16 32 64 96 128"
THREADS="8 16 32 64"

for threads in ${THREADS} ; do
   ./device-registration-stresstest results-${RELEASE}-${REQUESTS}-${threads}.data ${REQUESTS} ${threads}
done
