#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# Convert latitude and longitude to grid ID

from pyproj import Proj


# ###### Convert latitude and longitude to grid ID ##########################
def convert(lat, lon, place):
   p = Proj(proj='utm', ellps='WGS84', zone='33N')

   (utm_x, utm_y) = p(lon, lat)
   ssb_x = int(utm_x / 1000) * 1000 + 2000000   # round to thousands, add 2M by convention to avoid negative values
   ssb_y = int(utm_y / 1000) * 1000             # round to thousands
   ssbid =  ssb_x * 10000000 + ssb_y
   ssbid_str = str(ssb_x) + str(ssb_y)
   ok = (ssbid_str == str(ssbid))
   print("{:16s}\t{:12.6f}\t{:12.6f}\t{:16.4f}\t{:16.4f}\t{:12.0f}\t{:12.0f}\t{:16.0f}\t{:16s}\t{:d}".format(
            place, lat, lon, utm_x, utm_y, ssb_x, ssb_y, ssbid,   ssbid_str, ok))



# ###### Some tests #########################################################
print('place                      lat              lon              utm_x                  utm_y                    ssb_x           ssb_y       ssbid')

convert(59.9139, 10.7522,   'Oslo')
convert(60.3913, 5.3221,    'Bergen')
convert(78.2232, 15.6267,   'Longyearbyten')
convert(57.880,   7.4364,   'Mandal')

convert(90, 0,              'North Pole')
convert(-90, 0,             'South Pole')
convert(33.9416, -118.4085, 'Los Angeles')
convert(25.7617, -80.1918,  'Miami')
convert(51.5074, -0.1278,   'London')
convert(20.0444,  110.1983, 'Haikou')
convert(-37.8136, 144.963,  'Melbourne')
