{{- if .Values.fhi.autoscaling.enabled }}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "corona.fullname" . }}-fhi
  labels:
    component: fhi
    {{- include "corona.labels" . | nindent 4 }}
spec:
  maxReplicas: {{ .Values.fhi.autoscaling.maxReplicas }}
  minReplicas: {{ .Values.fhi.autoscaling.minReplicas }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ template "corona.fullname" . }}-fhi
  targetCPUUtilizationPercentage: {{ .Values.fhi.autoscaling.targetCPU }}
{{- end }}
