kind: Secret
apiVersion: v1
metadata:
  name: {{ template "corona.fullname" . }}-fhi
  labels:
    {{- include "corona.labels" . | nindent 4 }}
type: Opaque
data:
  AAD_TENANT_NAME: {{ .Values.activeDirectory.tenantName | b64enc | quote }}
  AAD_TENANT_ID: {{ .Values.activeDirectory.tenantId | b64enc | quote }}
  AAD_CLIENT_ID: {{ .Values.activeDirectory.clientId | b64enc | quote }}
  AAD_CLIENT_SECRET: {{ .Values.activeDirectory.clientSecret | b64enc | quote }}
  AAD_POLICY_NAME: {{ .Values.activeDirectory.policyName | b64enc | quote }}
  CLIENT_ID: {{ .Values.fhi.auth.username | b64enc | quote }}
  CLIENT_SECRET: {{ .Values.fhi.auth.password | b64enc | quote }}
  API_KEY: {{ .Values.fhi.auth.password | b64enc | quote }}
  IOTHUB_CONNECTION_STRING: {{ .Values.iothub.connectionString | b64enc | quote }}
  SEARCH_NAME: {{ .Values.search.name | b64enc | quote }}
  SEARCH_KEY: {{ .Values.search.key | b64enc | quote }}
  SEARCH_INDEX_NAME: {{ .Values.search.indexName | b64enc | quote }}
  AZURE_STORAGE_ACCOUNT_KEY: {{ .Values.storage.accountKey | b64enc | quote }}
  REDIS_PASSWORD: {{ .Values.redis.password | b64enc | quote }}
  {{- range $name, $value := .Values.fhi.secretEnv }}
  {{ $name }}: {{ $value | b64enc | quote }}
  {{- end }}
  tls.key: {{ .Values.tls.key | b64enc | quote }}
  tls.cert: {{ .Values.tls.cert | b64enc | quote }}
