service:
  type: NodePort
  ports:
    nodePort: 32567

resources:
  requests:
    memory: null
    cpu: null

corona:
  extraArgs:
  - "--logging=debug"

memcached:
  replicaCount: 1
  pdbMinAvailable: 0
