{{- if .Values.analysis.autoscaling.enabled }}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "corona.fullname" . }}-analysis
  labels:
    component: analysis
    {{- include "corona.labels" . | nindent 4 }}
spec:
  maxReplicas: {{ .Values.analysis.autoscaling.maxReplicas }}
  minReplicas: {{ .Values.analysis.autoscaling.minReplicas }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ template "corona.fullname" . }}-analysis
  targetCPUUtilizationPercentage: {{ .Values.analysis.autoscaling.targetCPU }}
{{- end }}
