kind: Secret
apiVersion: v1
metadata:
  name: {{ template "corona.fullname" . }}-analysis
  labels:
    {{- include "corona.labels" . | nindent 4 }}
type: Opaque
data:
  REDIS_PASSWORD: {{ .Values.redis.password | b64enc | quote }}
  {{- range $name, $value := .Values.analysis.secretEnv }}
  {{ $name }}: {{ $value | b64enc | quote }}
  {{- end }}
