apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "corona.fullname" . }}-onboarding
  labels:
    component: corona
    {{- include "corona.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.onboarding.replicas }}
  selector:
    matchLabels:
      component: onboarding
      {{- include "corona.matchLabels" . | nindent 6 }}
  {{- if .Values.onboarding.deploymentStrategy }}
  strategy:
    {{- .Values.onboarding.deploymentStrategy | toYaml | trimSuffix "\n" | nindent 4 }}
  {{- end }}
  template:
    metadata:
      labels:
        component: onboarding
        {{- include "corona.matchLabels" . | nindent 8 }}
      annotations:
        # This lets us autorestart when the secret changes!
        checksum/secret: {{ include (print .Template.BasePath "/onboarding/secret.yaml") . | sha256sum }}
        {{- if .Values.onboarding.annotations }}
        {{- .Values.onboarding.annotations | toYaml | trimSuffix "\n" | nindent 8 }}
        {{- end }}
        prometheus.io/scrape: 'true'
        prometheus.io/port: '8080'
        prometheus.io/path: '/metrics'
        prometheus.io/scheme: 'https'
    spec:
      nodeSelector: {{ toJson .Values.onboarding.nodeSelector }}
      volumes:
        - name: secret
          secret:
            secretName: {{ template "corona.fullname" . }}-onboarding
        {{- if .Values.onboarding.extraVolumes }}
        {{- .Values.onboarding.extraVolumes | toYaml | trimSuffix "\n" | nindent 8 }}
        {{- end }}
      {{- if .Values.onboarding.initContainers }}
      initContainers:
        {{- .Values.onboarding.initContainers | toYaml | trimSuffix "\n" | nindent 8 }}
      {{- end }}
      containers:
        {{- if .Values.onboarding.extraContainers }}
        {{- .Values.onboarding.extraContainers | toYaml | trimSuffix "\n" | nindent 8 }}
        {{- end }}
        - name: corona
          image: {{ .Values.onboarding.image }}
          volumeMounts:
            {{- range $name := list "blacklist.json" "jwks.json" "tls.key" "tls.cert" }}
            - mountPath: /etc/corona/{{ $name }}
              subPath: {{ $name }}
              name: secret
            {{- end }}

            {{- if .Values.onboarding.extraVolumeMounts }}
            {{- .Values.onboarding.extraVolumeMounts | toYaml | trimSuffix "\n" | nindent 12 }}
            {{- end }}
          resources:
            {{- .Values.onboarding.resources | toYaml | trimSuffix "\n" | nindent 12 }}
          {{- with .Values.onboarding.imagePullPolicy }}
          imagePullPolicy: {{ . }}
          {{- end }}
          env:
            - name: PYTHONUNBUFFERED
              value: "1"
            - name: HELM_RELEASE_NAME
              value: {{ .Release.Name | quote }}
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            {{- if .Values.tls.key }}
            - name: SSL_KEY
              value: /etc/corona/tls.key
            {{- end }}
            {{- if .Values.tls.cert }}
            - name: SSL_CERT
              value: /etc/corona/tls.cert
            {{- end }}
            # env from secret
            {{- $root := . }}
            {{- range .Values.onboarding.secretEnvKeys }}
            - name: {{ . }}
              valueFrom:
                secretKeyRef:
                  name: {{ template "corona.fullname" $root }}-onboarding
                  key: {{ . }}
            {{- end }}

            {{- range $name, $value := .Values.onboarding.extraEnv }}
            - name: {{ $name }}
              value: {{ $value | quote }}
            {{- end }}

            {{- range $name, $value := .Values.onboarding.secretEnv }}
            - name: {{ $name }}
              valueFrom:
                secretKeyRef:
                  name: {{ template "corona.fullname" $root }}-onboarding
                  key: {{ $name }}
            {{- end }}

          ports:
            - containerPort: 8080
              name: corona

          {{- if .Values.onboarding.livenessProbe.enabled }}
          livenessProbe:
            initialDelaySeconds: {{ .Values.onboarding.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.onboarding.livenessProbe.periodSeconds }}
            tcpSocket:
              port: corona
          {{- end }}

          {{- if .Values.onboarding.readinessProbe.enabled }}
          readinessProbe:
            initialDelaySeconds: {{ .Values.onboarding.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.onboarding.readinessProbe.periodSeconds }}
            tcpSocket:
              port: corona
          {{- end }}
