{{- if .Values.onboarding.autoscaling.enabled }}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "corona.fullname" . }}-onboarding
  labels:
    component: onboarding
    {{- include "corona.labels" . | nindent 4 }}
spec:
  maxReplicas: {{ .Values.onboarding.autoscaling.maxReplicas }}
  minReplicas: {{ .Values.onboarding.autoscaling.minReplicas }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ template "corona.fullname" . }}-onboarding
  targetCPUUtilizationPercentage: {{ .Values.onboarding.autoscaling.targetCPU }}
{{- end }}
