{{- if .Values.onboarding.ingress.enabled }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "corona.fullname" . }}-onboarding
  labels:
    component: onboarding
    {{- include "corona.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
spec:
  rules:
    {{ $root := . }}
    {{ range $host := .Values.onboarding.ingress.hosts }}
    - host: {{ $host }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ template "corona.fullname" $root }}-onboarding
              servicePort: 80
    {{ end }}
  tls:
    - secretName: {{ template "corona.fullname" . }}-onboarding-tls
      hosts:
      {{- range $host := .Values.onboarding.ingress.hosts }}
      - {{ $host }}
      {{- end }}
{{- end }}
