kind: Secret
apiVersion: v1
metadata:
  name: {{ template "corona.fullname" . }}-onboarding
  labels:
    {{- include "corona.labels" . | nindent 4 }}
type: Opaque
data:
  ID_SCOPE: {{ .Values.dps.idScope | b64enc | quote }}
  GROUP_SYMMETRIC_KEY: {{ .Values.dps.enrollmentGroupSymmetricKey | b64enc | quote }}
  AAD_TENANT_NAME: {{ .Values.activeDirectory.tenantName | b64enc | quote }}
  AAD_TENANT_ID: {{ .Values.activeDirectory.tenantId | b64enc | quote }}
  AAD_CLIENT_ID: {{ .Values.activeDirectory.clientId | b64enc | quote }}
  AAD_CLIENT_SECRET: {{ .Values.activeDirectory.clientSecret | b64enc | quote }}
  AAD_POLICY_NAME: {{ .Values.activeDirectory.policyName | b64enc | quote }}
  AAD_SCOPE: {{ .Values.activeDirectory.scope | b64enc | quote }}
  IOTHUB_CONNECTION_STRING: {{ .Values.iothub.connectionString | b64enc | quote }}
  {{- range $name, $value := .Values.onboarding.secretEnv }}
  {{ $name }}: {{ $value | b64enc | quote }}
  {{- end }}
  blacklist.json: {{ .Values.onboarding.blacklist | toJson | b64enc | quote }}
  jwks.json: {{ .Values.activeDirectory.jwksJson | b64enc | quote }}
  tls.key: {{ .Values.tls.key | b64enc | quote }}
  tls.cert: {{ .Values.tls.cert | b64enc | quote }}
