kind: Secret
apiVersion: v1
metadata:
  name: {{ template "corona.fullname" . }}-delete
  labels:
    {{- include "corona.labels" . | nindent 4 }}
type: Opaque
data:
  AAD_TENANT_NAME: {{ .Values.activeDirectory.tenantName | b64enc | quote }}
  AAD_TENANT_ID: {{ .Values.activeDirectory.tenantId | b64enc | quote }}
  AAD_CLIENT_ID: {{ .Values.activeDirectory.clientId | b64enc | quote }}
  AAD_CLIENT_SECRET: {{ .Values.activeDirectory.clientSecret | b64enc | quote }}
  IOTHUB_CONNECTION_STRING: {{ .Values.iothub.connectionString | b64enc | quote }}
  AZURE_STORAGE_ACCOUNT_KEY: {{ .Values.storage.accountKey | b64enc | quote }}
  {{- range $name, $value := .Values.delete.secretEnv }}
  {{ $name }}: {{ $value | b64enc | quote }}
  {{- end }}
