# this is the encrypted helm values.yaml
# tokens and such go here and they will be encrypted in the repo
grafana:
  adminUser: grafana-admin
  adminPassword: 

activeDirectory:
  tenantId: ""
  tenantName: "devsmittestopp"
  clientId: ""
  clientSecret: ""
  policyName: "b2c_1a_phone_susi"

storage:
  accountKey: ""

search:
  key: ""
  name: "smittesearch"
  indexName: "azureblob-index"

dps:
  idScope: ""
  enrollmentGroupSymmetricKey: ""

iothub:
  connectionString: HostName=iot-smittestopp-dev.azure-devices.net;SharedAccessKeyName=iothubowner;SharedAccessKey=

tls:
  # key is live/dev.corona.nntb.no/privkey.pem
  key: |
    -----BEGIN PRIVATE KEY-----
    -----END PRIVATE KEY-----
  # cert is live/dev.corona.nntb.no/fullchain.pem
  cert: |
    -----BEGIN CERTIFICATE-----
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    -----END CERTIFICATE-----

onboarding:
  secretEnv:
    APPLICATIONINSIGHTS_CONNECTION_STRING: "InstrumentationKey="
    SQL_SERVER: sqlserver-smittestopp-devne.database.windows.net
    SQL_DATABASE: sql01-smittestopp-dev
    SQL_TENANT_ID: ""
    SQL_CLIENT_ID: ""
    SQL_CLIENT_SECRET: ""
  extraEnv:
    TESTER_NUMBERS: ""

fhi:
  secretEnv:
    SQL_SERVER: sqlserver-smittestopp-devne.database.windows.net
    SQL_DATABASE: sql01-smittestopp-dev
    SQL_TENANT_ID: ""
    SQL_CLIENT_ID: ""
    SQL_CLIENT_SECRET: ""
  auth:
    username: "api-gateway"
    password: ""

analysis:
  secretEnv:
    SQL_SERVER: sqlserver-smittestopp-devne.database.windows.net
    SQL_DATABASE: sql01-smittestopp-dev
    SQL_TENANT_ID: ""
    SQL_CLIENT_ID: ""
    SQL_CLIENT_SECRET: ""

delete:
  secretEnv:
    SQL_SERVER: sqlserver-smittestopp-devne.database.windows.net
    SQL_DATABASE: sql01-smittestopp-dev
    SQL_TENANT_ID: ""
    SQL_CLIENT_ID: ""
    SQL_CLIENT_SECRET: ""

redis:
  password: ""

